Repository SIT-SandBox/thai-bad-words, pull requests merged in 2025-01, with the labels that each got.

#2 update Readme & add license
  LICENSE
  README.md
  README.th.md
Labels: documentation

#15 New Function! - scanBadWords();
  .github/workflows/main.yml
  .github/workflows/npm-publish.yml
  README.md
  README.th.md
  package-lock.json
  package.json
  src/index.ts
  src/types/index.d.ts
  src/words/wordLists.ts
Labels: new-feature

#20 update
  .github/workflows/enforce-dev-branch.yml
  .gitignore
  README.md
  README.th.md
  package.json
  src/index.test.ts
  src/index.ts
  src/types/index.d.ts
  src/words/wordLists.ts
Labels: documentation, enhancement
